# Generated by Django 2.2.2 on 2019-06-28 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('home_town', models.CharField(max_length=100, null=True)),
                ('home_region', models.CharField(max_length=100, null=True)),
                ('home_country', models.CharField(max_length=100, null=True)),
                ('home_latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('home_longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('birth_day', models.IntegerField(null=True)),
                ('birth_month', models.IntegerField(null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('shoots', models.CharField(choices=[('R', 'R'), ('L', 'L')], max_length=2, null=True)),
                ('primary_position', models.CharField(choices=[('RW', 'RW'), ('LW', 'LW'), ('C', 'C'), ('D', 'D'), ('G', 'G')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(null=True)),
                ('goals', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('pim', models.IntegerField(null=True)),
                ('shots', models.IntegerField(null=True)),
                ('hits', models.IntegerField(null=True)),
                ('pp_goals', models.IntegerField(null=True)),
                ('pp_assists', models.IntegerField(null=True)),
                ('pp_toi', models.IntegerField(null=True)),
                ('ev_toi', models.IntegerField(null=True)),
                ('faceoff_pct', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shooting_pct', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gw_goals', models.IntegerField(null=True)),
                ('ot_goals', models.IntegerField(null=True)),
                ('sh_goals', models.IntegerField(null=True)),
                ('sh_points', models.IntegerField(null=True)),
                ('sh_toi', models.IntegerField(null=True)),
                ('blocks', models.IntegerField(null=True)),
                ('plus_minus', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('shifts', models.IntegerField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hockeystats.Person')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hockeystats.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hockeystats.Team')),
            ],
        ),
    ]
