# Generated by Django 2.2.2 on 2019-06-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockeystats', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statline',
            index=models.Index(fields=['person', 'team', 'season'], name='hockeystats_person__917515_idx'),
        ),
    ]
